# Generated by Django 5.1.5 on 2025-04-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cakes', 'Cakes'), ('Cookies', 'Cookies'), ('Pastries', 'Pastries'), ('Muffins', 'Muffins'), ('Breads', 'Breads'), ('Brownies', 'Brownies')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
