# Generated by Django 5.1.5 on 2025-04-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_alter_review_comment_alter_review_rating_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='In Progress', max_length=20),
        ),
    ]
