# Generated by Django 5.1.5 on 2025-04-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0006_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Pickup', 'Pickup')], default='Delivery', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='dietary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='flavor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='topping',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
