# Generated by Django 5.1.5 on 2025-04-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0009_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='points_redeemed',
            field=models.IntegerField(default=0),
        ),
    ]
