# Generated by Django 5.1.5 on 2025-04-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0010_order_points_earned_order_points_redeemed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
    ]
